name: 'Code checks'

on: [push]

env:
  cmssw_ver: CMSSW_10_2_10

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a CVMFS Docker image & set environment
      env:
        build_image: clelange/cc7-cmssw-cvmfs:latest
        docker_options: -t - P --cap-add SYS_ADMIN --cap-add=MKNOD --security-opt apparmor=unconfined -e CVMFS_MOUNTS="cms.cern.ch" --device /dev/fuse -v /sys/fs/cgroup:/sys/fs/cgroup:ro /bin/bash
      run: docker run ${{ env.docker_options }} ${{ env.build_image }} -c "source /cvmfs/cms.cern.ch/cmsset_default.sh"

