name: 'Code checks'

on: [push]

env:
  cmssw_ver: CMSSW_10_2_10

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        uses: Laurits7/Test@master


    # steps:
    # - uses: actions/checkout@v2
    # - name: Pull the Docker Image
    #   run: docker pull clelange/cc7-cmssw-cvmfs:latest
    # - name: Run Docker Image

    # container: clelange/cc7-cmssw-cvmfs:latest
    # steps:
    #   - name: Test
    #     run: source /cvmfs/cms.cern.ch/cmsset_default.sh


      # run: |
      #     docker run \
      #     --cap-add SYS_ADMIN \
      #     --cap-add=MKNOD \
      #     --security-opt apparmor=unconfined \
      #     -e CVMFS_MOUNTS="cms.cern.ch" \
      #     --device /dev/fuse \
      #     -it clelange/cc7-cmssw-cvmfs:latest \
      #     /bin/bash

