name: 'Code checks'

on: [push]

env:
  cmssw_ver: CMSSW_10_2_10
  repo_url: https://github.com/Laurits7/Saving

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run docker Image
        env:
          build_image: clelange/cc7-cmssw-cvmfs:latest
          docker_options: --cap-add SYS_ADMIN --cap-add=MKNOD --security-opt apparmor=unconfined -e CVMFS_MOUNTS="cms.cern.ch" -v /home/runner/work/Saving/Saving:/home/cmsusr/results --device /dev/fuse -i
        run: |
            docker run ${{ env.docker_options }} ${{ env.build_image }} /bin/bash \
            -c 'source /cvmfs/cms.cern.ch/cmsset_default.sh && echo Succeeded to source || exit_on_error "Failed to source"!; \
             scramv1 project CMSSW ${{ env.cmssw_ver }}; cd ${{ env.cmssw_ver }}/src ; "eval `scramv1 runtime -sh`" ; \
             echo ${{ env.cmssw_ver }}/src/machineLearning/machineLearning; git clone ${{ env.repo_url}} machineLearning/machineLearning;\
             cd machineLearning/machineLearning; sudo python -m pip install pycodestyle; \
             pycodestyle . &> ~/results/output.txt '
        # Can't use the alias cmsrel, would need to echo it to .bashrc. Though this is the only place we need that alias.

# /commit/${{ github.sha }}

      #   run: |
      #     docker run \
      #     --cap-add SYS_ADMIN \
      #     --cap-add=MKNOD \
      #     --security-opt apparmor=unconfined \
      #     -e CVMFS_MOUNTS="cms.cern.ch" \
      #     --device /dev/fuse \
      #     -i clelange/cc7-cmssw-cvmfs:latest \
      #     /bin/bash
      # - name: Take a look around
      #   run: pwd && ls
      # - name: source
      #   run: ls /cvmfs


    # steps:
    # - uses: actions/checkout@v2
    # - name: Pull the Docker Image
    #   run: docker pull clelange/cc7-cmssw-cvmfs:latest
    # - name: Run Docker Image

    # container: clelange/cc7-cmssw-cvmfs:latest
    # steps:
    #   - name: Test
    #     run: source /cvmfs/cms.cern.ch/cmsset_default.sh


