name: 'Code checks'

on: [push]

env:
  cmssw_ver: CMSSW_10_2_10

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run docker Image
        env:
          build_image: clelange/cc7-cmssw-cvmfs:latest
          docker_options: --cap-add SYS_ADMIN --cap-add=MKNOD --security-opt apparmor=unconfined -e CVMFS_MOUNTS="cms.cern.ch" --device /dev/fuse -i /bin/bash
        run: docker run ${{ env.docker_options }} ${{ env.build_image }}
      - name:
        run: docker images


      #   run: |
      #     docker run \
      #     --cap-add SYS_ADMIN \
      #     --cap-add=MKNOD \
      #     --security-opt apparmor=unconfined \
      #     -e CVMFS_MOUNTS="cms.cern.ch" \
      #     --device /dev/fuse \
      #     -i clelange/cc7-cmssw-cvmfs:latest \
      #     /bin/bash
      # - name: Take a look around
      #   run: pwd && ls
      # - name: source
      #   run: ls /cvmfs


    # steps:
    # - uses: actions/checkout@v2
    # - name: Pull the Docker Image
    #   run: docker pull clelange/cc7-cmssw-cvmfs:latest
    # - name: Run Docker Image

    # container: clelange/cc7-cmssw-cvmfs:latest
    # steps:
    #   - name: Test
    #     run: source /cvmfs/cms.cern.ch/cmsset_default.sh


